---
services:
  backend:
    container_name: "backend-my-diary"
    depends_on:
      - postgres
    build: ./backend
    links:
      - postgres
    ports:
      - '3000:3000'
    restart: on-failure
    volumes:
      - data-files:/app/dist/static
  frontend:
    container_name: "frontend-my-diary"
    build: ./frontend
    ports: 
    - "8081:80"
    tty: true
    stdin_open: true
    restart: on-failure
    depends_on: 
     - backend
  postgres:
    container_name: "postgres"
    environment:
      - POSTGRES_DB=my_diary_db
      - POSTGRES_USER=userDiary
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_HOST=postgres
      - POSTGRES_PGDATA=/var/lib/postgresql/pgdata
    image: postgres
    ports:
      - '5432:5432'
    restart: on-failure
    volumes:
      - data-files:/app/dist/static
volumes:
    data:
    data-files:    
version: '3.9'